services:
  - type: web
    name: usalama-wa-watu-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: streamlit run app/app.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
